# Generated by Django 3.2.7 on 2021-10-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('ticker', models.TextField(blank=True, null=True, unique=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('rateusd', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
