# Generated by Django 3.2.7 on 2021-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('ticker', models.TextField(unique=True)),
                ('image', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
