# Generated by Django 3.2.7 on 2021-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='rateUSD',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
