# Generated by Django 3.2.7 on 2021-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_rateusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
