# Generated by Django 3.2.7 on 2021-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20210905_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
