# Generated by Django 3.2.7 on 2021-09-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_alter_coin_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='rateUSD',
            new_name='rateusd',
        ),
    ]
