# Generated by Django 3.2.7 on 2021-09-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_rename_rateusd_coin_rateusd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='rateusd',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ticker',
        ),
    ]
