# Generated by Django 3.2.7 on 2021-09-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_auto_20210908_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='rateusd',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ticker',
        ),
    ]
