# Generated by Django 3.2.7 on 2021-09-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_auto_20210908_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
