# Generated by Django 3.2.7 on 2021-09-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0015_coin_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='rateusd',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ticker',
        ),
    ]
