# Generated by Django 3.2.7 on 2021-09-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_auto_20210929_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='rateusd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='coin',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='ticker',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
