POST http://127.0.0.1:8000/dj-rest-auth/register/
Content-Type: application/json

{
    "username":"test666",
    "password1": "12345",
    "password2": "12345",
    "email": "test666@test.com"
}


### login
POST http://127.0.0.1:8000/dj-rest-auth/login/
Content-Type: application/json

{
    "username":"test2",
    "password": "12345"
}

### logout
POST http://127.0.0.1:8000/dj-rest-auth/logout/
Content-Type: application/json


### refresh token
POST  http://127.0.0.1:8000/dj-rest-auth/token/refresh/
Content-Type: application/json 

{
    "refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYzMTk4MjI5NSwianRpIjoiMjM4OTNkMDQxOTA0NDY1MGFiZmUxMmM0NDI1NWNlMGYiLCJ1c2VyX2lkIjoxfQ.z_JfLmzWhbxGc-HVHZr2mqLW1okzxGzCvWxfCTwJSN4"
}

### list all coins

GET  http://127.0.0.1:8000/coins/



### get balances of user
GET  http://127.0.0.1:8000/balances/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMyNDMwMDI1LCJqdGkiOiIyNzRkOGRkMmQ3Mjk0OWEzYTA2ZDk2NTdkNDQzODYwYyIsInVzZXJfaWQiOjN9.WyDtzS8X5pwzDCjGrO2kjOVebeFfEHdM_phOrcsiUMs

### add coin to balance
POST  http://127.0.0.1:8000/balances/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMyNDI0NjcxLCJqdGkiOiIxMTNlMjgxNjIwNDc0MTk4ODkyMTBiYzFlOTUxNTVlMyIsInVzZXJfaWQiOjN9.wMxK4QeXQNCR898oyvu53rXgjWwUEdpLQUvtTVrxth4
Content-Type: application/json

{
    "coinID":5247,
    "quantity": "25",
    "updated_on":"2019-01-19T00:00:00Z"
}

### update balance

PUT  http://127.0.0.1:8000/balances/4/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMxNjQ3NTU3LCJqdGkiOiJiNjJiMTRiNDkwMDU0MDFjYWNiNTRiZmU3NmQ5YjkzMCIsInVzZXJfaWQiOjN9.iLh__JAuXOt6jMKEGIJf619qy6uOyVDAZZ-FkEEwEic
Content-Type: application/json

{
    "quantity": "33",
    "updated_on":"2019-10-20T00:00:00Z"
}