POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username":"test666",
    "password": "12345",
    "email": "test666@test.com"
}


### login
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username":"test2",
    "password": "12345"
}


### refresh token
POST  http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json 

{
    "refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYzMTIxMzE4MiwianRpIjoiMjg4MzZjNzZlYzQwNDI5YWI4YjhiNWU2NWRhNzdhNzkiLCJ1c2VyX2lkIjozfQ.wGU3GBNdn8uziOZRE17jS6nnhMLbJgfKrtwwLX_hfuc"
}

### list all coins

GET  http://127.0.0.1:8000/coins/



### get balances of user
GET  http://127.0.0.1:8000/balances/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMxMTI3MTY1LCJqdGkiOiI3NWVmYmNiNmZhZTg0NjNhYmVlZDBiNGY3MTFlZWZkZSIsInVzZXJfaWQiOjN9.sizwgnCBjN8as1YneNpEyDg_O_6kPi8bxYPMf6uCZF8

### add coin to balance
POST  http://127.0.0.1:8000/balances/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMxMTI3MTY1LCJqdGkiOiI3NWVmYmNiNmZhZTg0NjNhYmVlZDBiNGY3MTFlZWZkZSIsInVzZXJfaWQiOjN9.sizwgnCBjN8as1YneNpEyDg_O_6kPi8bxYPMf6uCZF8
Content-Type: application/json

{
    "coin":"234",
    "quantity": "978",
    "updated_on":"2019-01-19T00:00:00Z"
}

### update balance

PUT  http://127.0.0.1:8000/balances/1/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMxMTI2NzIxLCJqdGkiOiJhMzVkNzgyN2E2Mjc0YTI4YjNhYmVhMGQ4Nzk4MTA1OSIsInVzZXJfaWQiOjN9.aS1Ll63AGBNAPpmxnGLSv9rdh7sHXRp6tUK6SqbeuKY
Content-Type: application/json

{
    "quantity": "3",
    "updated_on":"2019-10-20T00:00:00Z"
}