# Generated by Django 3.2.7 on 2021-09-29 23:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0015_coin_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='coins.coin')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.UniqueConstraint(fields=('owner', 'coin'), name='coinId_ownerId'),
        ),
    ]
