# Generated by Django 3.2.7 on 2021-09-05 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_rateusd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='rateUSD',
        ),
        migrations.AddField(
            model_name='balance',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin', to='coins.coin'),
        ),
        migrations.AddField(
            model_name='balance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.UniqueConstraint(fields=('owner', 'coin'), name='coinId_ownerId'),
        ),
    ]
