# Generated by Django 3.2.7 on 2021-09-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0005_auto_20210910_1946'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balance',
            name='coinId_ownerId',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='updated_on',
        ),
    ]
