# Generated by Django 3.2.7 on 2021-09-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0009_auto_20210910_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
