# Generated by Django 3.2.7 on 2021-09-10 20:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_auto_20210908_2114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balances', '0011_auto_20210910_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin', to='coins.coin'),
        ),
        migrations.AddField(
            model_name='balance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balance',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.UniqueConstraint(fields=('owner', 'coin'), name='coinId_ownerId'),
        ),
    ]
