# Generated by Django 3.2.7 on 2021-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0012_auto_20210910_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
