# Generated by Django 3.2.7 on 2021-09-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_auto_20210908_2114'),
        ('balances', '0015_auto_20210913_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='coin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='coins.coin'),
        ),
    ]
