# Generated by Django 3.2.7 on 2021-09-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0020_auto_20210929_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
