# Generated by Django 3.2.7 on 2021-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0021_alter_balance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
