# Generated by Django 3.2.7 on 2021-09-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0027_auto_20210929_1844'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balance',
            name='coinId_ownerId',
        ),
    ]
