# Generated by Django 3.2.7 on 2021-09-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0032_auto_20210929_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
